import 'package:flutter/material.dart';
import 'planet_detail_screen.dart'; // make sure this import matches your file location

final List<Map<String, dynamic>> planetData = [
  {
    "Planet Name": "Sun",
    "3D Model": "sun.glb",
    "Title": "The Sun: Our Solar System's Star",
    "About": "The Sun is the heart of our solar system, a massive ball of burning gases...",
    "Distance from Sun (km)": "0",
    "Length of Day (hours)": "0",
    "Orbital Period (Earth years)": "0.00",
    "Radius (km)": "695,700",
    "Mass (kg)": "1.989 × 10³⁰",
    "Gravity (m/s²)": "274.00",
    "Surface Area (km²)": "6.09 × 10¹²",
  },
  {
    "Planet Name": "Mercury",
    "3D Model": "mercury.glb",
    "Title": "Mercury: The Closest Planet",
    "About": "Mercury is the smallest planet in our solar system and nearest to the Sun...",
    "Distance from Sun (km)": "57,909,227",
    "Length of Day (hours)": "1407.60",
    "Orbital Period (Earth years)": "0.24",
    "Radius (km)": "2,439.70",
    "Mass (kg)": "3.301 × 10²³",
    "Gravity (m/s²)": "3.70",
    "Surface Area (km²)": "7.48 × 10⁷",
  },
  {
    "Planet Name": "Venus",
    "3D Model": "venus.glb",
    "Title": "Venus: Earth's Toxic Twin",
    "About": "Venus is often referred to as Earth's twin due to its similar size, but it's extremely hot...",
    "Distance from Sun (km)": "108,209,072",
    "Length of Day (hours)": "5832.20",
    "Orbital Period (Earth years)": "0.62",
    "Radius (km)": "6,051.80",
    "Mass (kg)": "4.867 × 10²⁴",
    "Gravity (m/s²)": "8.87",
    "Surface Area (km²)": "4.60 × 10⁸",
  },
  {
    "Planet Name": "Earth",
    "3D Model": "earth.glb",
    "Title": "Earth: Our Blue Marble",
    "About": "Earth is the only known planet in the universe that supports life...",
    "Distance from Sun (km)": "149,598,026",
    "Length of Day (hours)": "23.93",
    "Orbital Period (Earth years)": "1.00",
    "Radius (km)": "6,371",
    "Mass (kg)": "5.972 × 10²⁴",
    "Gravity (m/s²)": "9.81",
    "Surface Area (km²)": "5.10 × 10⁸",
  },
  {
    "Planet Name": "Mars",
    "3D Model": "mars.glb",
    "Title": "Mars: The Red Planet",
    "About": "Mars, often called the Red Planet, is the second smallest planet in the solar system...",
    "Distance from Sun (km)": "227,943,824",
    "Length of Day (hours)": "24.62",
    "Orbital Period (Earth years)": "1.88",
    "Radius (km)": "3,389.50",
    "Mass (kg)": "6.39 × 10²³",
    "Gravity (m/s²)": "3.71",
    "Surface Area (km²)": "1.45 × 10⁸",
  },
  {
    "Planet Name": "Jupiter",
    "3D Model": "jupiter.glb",
    "Title": "Jupiter: The Gas Giant",
    "About": "Jupiter is the largest planet in our solar system, known for its Great Red Spot...",
    "Distance from Sun (km)": "778,340,821",
    "Length of Day (hours)": "9.93",
    "Orbital Period (Earth years)": "11.86",
    "Radius (km)": "69,911",
    "Mass (kg)": "1.898 × 10²⁷",
    "Gravity (m/s²)": "24.79",
    "Surface Area (km²)": "6.14 × 10¹⁰",
  },
  {
    "Planet Name": "Saturn",
    "3D Model": "saturn.glb",
    "Title": "Saturn: The Ringed Planet",
    "About": "Saturn is famous for its beautiful rings made of ice and rock particles...",
    "Distance from Sun (km)": "1,426,666,422",
    "Length of Day (hours)": "10.7",
    "Orbital Period (Earth years)": "29.45",
    "Radius (km)": "58,232",
    "Mass (kg)": "5.683 × 10²⁶",
    "Gravity (m/s²)": "10.44",
    "Surface Area (km²)": "4.27 × 10¹⁰",
  },
  {
    "Planet Name": "Uranus",
    "3D Model": "uranus.glb",
    "Title": "Uranus: The Tilted Ice Giant",
    "About": "Uranus has a unique rotation axis tilted over 90 degrees and is an icy giant...",
    "Distance from Sun (km)": "2,870,658,186",
    "Length of Day (hours)": "17.24",
    "Orbital Period (Earth years)": "84.01",
    "Radius (km)": "25,362",
    "Mass (kg)": "8.681 × 10²⁵",
    "Gravity (m/s²)": "8.69",
    "Surface Area (km²)": "8.1 × 10⁹",
  },
  {
    "Planet Name": "Neptune",
    "3D Model": "neptune.glb",
    "Title": "Neptune: The Windy Blue World",
    "About": "Neptune is the farthest planet from the Sun, known for its intense winds and deep blue color...",
    "Distance from Sun (km)": "4,498,396,441",
    "Length of Day (hours)": "16.11",
    "Orbital Period (Earth years)": "164.79",
    "Radius (km)": "24,622",
    "Mass (kg)": "1.024 × 10²⁶",
    "Gravity (m/s²)": "11.15",
    "Surface Area (km²)": "7.6 × 10⁹",
  }
];

void navigateToPlanetDetail(BuildContext context, String planetName) {
  final selectedPlanetData = planetData.firstWhere(
        (planet) => planet['Planet Name'] == planetName,
    orElse: () => throw Exception('Planet not found'),
  );

  Navigator.push(
    context,
    MaterialPageRoute(
      builder: (context) => PlanetDetailScreen(data: selectedPlanetData),
    ),
  );
}
