final List<Map<String, dynamic>> planetData = [
  {
    "Planet Name": "Mercury",
    "3D Model": "mercury.glb",
    "Title": "Mercury: The Closest Planet",
    "About": "Mercury is the smallest planet in our solar system and nearest to the Sun. It has a solid, cratered surface, much like the Earth's moon. It doesn't have any moons or rings and completes an orbit around the Sun in just 88 Earth days.",
    "Distance from Sun (km)": "57,909,227",
    "Length of Day (hours)": "1407.60",
    "Orbital Period (Earth years)": "0.24",
    "Radius (km)": "2,439.70",
    "Mass (kg)": "3.301 × 10²³",
    "Gravity (m/s²)": "3.70",
    "Surface Area (km²)": "7.48 × 10⁷",
  },
  {
    "Planet Name": "Venus",
    "3D Model": "venus.glb",
    "Title": "Venus: Earth's Twin",
    "About": "Venus is the second planet from the Sun and is similar in structure and size to Earth, but it has a thick, toxic atmosphere that traps heat. Surface temperatures are hot enough to melt lead.",
    "Distance from Sun (km)": "108,209,475",
    "Length of Day (hours)": "5832.50",
    "Orbital Period (Earth years)": "0.62",
    "Radius (km)": "6,051.80",
    "Mass (kg)": "4.867 × 10²⁴",
    "Gravity (m/s²)": "8.87",
    "Surface Area (km²)": "4.6 × 10⁸",
  },
  {
    "Planet Name": "Earth",
    "3D Model": "earth.glb",
    "Title": "Earth: Our Home Planet",
    "About": "Earth is the third planet from the Sun and the only astronomical object known to harbor life. Its atmosphere and magnetic field protect life from harmful solar radiation.",
    "Distance from Sun (km)": "149,598,262",
    "Length of Day (hours)": "24.00",
    "Orbital Period (Earth years)": "1.00",
    "Radius (km)": "6,371.00",
    "Mass (kg)": "5.972 × 10²⁴",
    "Gravity (m/s²)": "9.81",
    "Surface Area (km²)": "5.1 × 10⁸",
  },
  {
    "Planet Name": "Mars",
    "3D Model": "mars.glb",
    "Title": "Mars: The Red Planet",
    "About": "Mars is the fourth planet from the Sun and is known for its red appearance due to iron oxide on its surface. It has the tallest volcano and the deepest canyon in the solar system.",
    "Distance from Sun (km)": "227,943,824",
    "Length of Day (hours)": "24.60",
    "Orbital Period (Earth years)": "1.88",
    "Radius (km)": "3,389.50",
    "Mass (kg)": "6.417 × 10²³",
    "Gravity (m/s²)": "3.71",
    "Surface Area (km²)": "1.44 × 10⁸",
  },
  {
    "Planet Name": "Jupiter",
    "3D Model": "jupiter.glb",
    "Title": "Jupiter: The Gas Giant",
    "About": "Jupiter is the largest planet in our solar system. It's known for its massive size, strong magnetic field, and Great Red Spot—a giant storm larger than Earth.",
    "Distance from Sun (km)": "778,340,821",
    "Length of Day (hours)": "9.93",
    "Orbital Period (Earth years)": "11.86",
    "Radius (km)": "69,911.00",
    "Mass (kg)": "1.898 × 10²⁷",
    "Gravity (m/s²)": "24.79",
    "Surface Area (km²)": "6.14 × 10¹⁰",
  },
  {
    "Planet Name": "Saturn",
    "3D Model": "saturn.glb",
    "Title": "Saturn: The Ringed Planet",
    "About": "Saturn is famous for its stunning rings. It's the second-largest planet in the solar system and has more than 80 moons.",
    "Distance from Sun (km)": "1,426,666,422",
    "Length of Day (hours)": "10.70",
    "Orbital Period (Earth years)": "29.45",
    "Radius (km)": "58,232.00",
    "Mass (kg)": "5.683 × 10²⁶",
    "Gravity (m/s²)": "10.44",
    "Surface Area (km²)": "4.27 × 10¹⁰",
  },
  {
    "Planet Name": "Uranus",
    "3D Model": "uranus.glb",
    "Title": "Uranus: The Tilted Planet",
    "About": "Uranus rotates on its side, making it unique in the solar system. It's a cold, ice giant with faint rings and a blue-green color due to methane in its atmosphere.",
    "Distance from Sun (km)": "2,870,658,186",
    "Length of Day (hours)": "17.20",
    "Orbital Period (Earth years)": "84.01",
    "Radius (km)": "25,362.00",
    "Mass (kg)": "8.681 × 10²⁵",
    "Gravity (m/s²)": "8.69",
    "Surface Area (km²)": "8.08 × 10⁹",
  },
  {
    "Planet Name": "Neptune",
    "3D Model": "neptune.glb",
    "Title": "Neptune: The Windy Planet",
    "About": "Neptune is the farthest planet from the Sun and has the strongest winds in the solar system. It's a deep blue ice giant with 14 known moons.",
    "Distance from Sun (km)": "4,498,396,441",
    "Length of Day (hours)": "16.11",
    "Orbital Period (Earth years)": "164.8",
    "Radius (km)": "24,622.00",
    "Mass (kg)": "1.024 × 10²⁶",
    "Gravity (m/s²)": "11.15",
    "Surface Area (km²)": "7.64 × 10⁹",
  },
];
